/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JFrame;

/**
 *
 * @author sebas
 */
public class Login extends JFrame {

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        textoTitulo2 = new javax.swing.JLabel();
        passUser = new javax.swing.JPasswordField();
        botonIngresar = new javax.swing.JButton();
        textoTitulo = new javax.swing.JLabel();
        perfiles = new javax.swing.JComboBox<>();
        textoPerfil = new javax.swing.JLabel();
        background2 = new javax.swing.JPanel();
        imagen1 = new javax.swing.JLabel();
        inputUser = new javax.swing.JTextField();
        userTxt = new javax.swing.JLabel();
        passTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conexión U");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(183, 214, 163));
        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        background.setForeground(new java.awt.Color(0, 0, 0));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoTitulo2.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        textoTitulo2.setForeground(new java.awt.Color(0, 0, 0));
        textoTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoTitulo2.setText("Inicio de sesión");
        textoTitulo2.setToolTipText("");
        textoTitulo2.setAutoscrolls(true);
        background.add(textoTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 270, 40));

        passUser.setBackground(new java.awt.Color(255, 255, 255));
        passUser.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        passUser.setForeground(new java.awt.Color(153, 153, 153));
        passUser.setText("****");
        passUser.setToolTipText("");
        passUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        passUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passUserMousePressed(evt);
            }
        });
        passUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passUserActionPerformed(evt);
            }
        });
        background.add(passUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 230, 30));

        botonIngresar.setBackground(new java.awt.Color(255, 255, 255));
        botonIngresar.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        botonIngresar.setForeground(new java.awt.Color(0, 0, 0));
        botonIngresar.setText("Ingresar");
        botonIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonIngresarMouseClicked(evt);
            }
        });
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });
        background.add(botonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 120, 30));

        textoTitulo.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        textoTitulo.setForeground(new java.awt.Color(0, 0, 0));
        textoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoTitulo.setText("Conexión U");
        textoTitulo.setToolTipText("");
        textoTitulo.setAutoscrolls(true);
        background.add(textoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 270, 40));

        perfiles.setBackground(new java.awt.Color(255, 255, 255));
        perfiles.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        perfiles.setForeground(new java.awt.Color(0, 0, 0));
        perfiles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Docente", "Mentor", "Estudiante" }));
        perfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilesActionPerformed(evt);
            }
        });
        background.add(perfiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 150, 30));

        textoPerfil.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        textoPerfil.setForeground(new java.awt.Color(0, 0, 0));
        textoPerfil.setText("Seleccione un perfil");
        background.add(textoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, -1, -1));

        background2.setBackground(new java.awt.Color(91, 140, 58));
        background2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Imagen2.png"))); // NOI18N
        background2.add(imagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 300, 340));

        background.add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 610));

        inputUser.setBackground(new java.awt.Color(255, 255, 255));
        inputUser.setFont(new java.awt.Font("Rockwell", 0, 15)); // NOI18N
        inputUser.setForeground(new java.awt.Color(153, 153, 153));
        inputUser.setText("Ingrese su nombre de usuario");
        inputUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        inputUser.setMargin(new java.awt.Insets(0, 10, 0, 0));
        inputUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputUserFocusGained(evt);
            }
        });
        background.add(inputUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 230, 30));

        userTxt.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        userTxt.setForeground(new java.awt.Color(0, 0, 0));
        userTxt.setText("Usuario");
        background.add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, -1, -1));

        passTxt.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        passTxt.setForeground(new java.awt.Color(0, 0, 0));
        passTxt.setText("Contraseña");
        background.add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1016, 669));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passUserActionPerformed

    private void passUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passUserMousePressed
        
        if(String.valueOf(passUser.getPassword()).equals("****")){
            
            passUser.setText("");
            passUser.setForeground(Color.black);
        }
        
        if (inputUser.getText().isEmpty()){
            inputUser.setText("Ingrese su nombre de usuario");
        }
        
    }//GEN-LAST:event_passUserMousePressed

    private void botonIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIngresarMouseClicked
        
         
        if (inputUser.getText().equals("Ingrese su nombre de usuario") || inputUser.getText().equals("") || String.valueOf(passUser.getPassword()).equals("****")){
            JOptionPane.showMessageDialog(null, "Los campos están vacíos");
        } else{
            JOptionPane.showMessageDialog(null, "El usuario ingresado es: " + inputUser.getText()+"\n"+
                    "La contraseña ingresada es: " + String.valueOf(passUser.getPassword()));
        }
        
        switch(perfiles.getSelectedItem().toString()){
            
            case "Docente" -> {
                JOptionPane.showMessageDialog(this, "Seleccionó el perfil de docente");
            }
            case "Mentor" ->{
                JOptionPane.showMessageDialog(this, "Seleccionó el perfil de mentor");
            }
            case "Estudiante" ->{
                JOptionPane.showMessageDialog(this, "Seleccionó el perfil de estudiante");
            }
        }
        
        
    }//GEN-LAST:event_botonIngresarMouseClicked

    private void perfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilesActionPerformed

    }//GEN-LAST:event_perfilesActionPerformed

    private void inputUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputUserFocusGained
        
        if (inputUser.getText().equals("Ingrese su nombre de usuario")){
        
        
            inputUser.setText("");
            
        }
        
    }//GEN-LAST:event_inputUserFocusGained

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
            
            
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel background2;
    private javax.swing.JButton botonIngresar;
    private javax.swing.JLabel imagen1;
    private javax.swing.JTextField inputUser;
    private javax.swing.JLabel passTxt;
    private javax.swing.JPasswordField passUser;
    private javax.swing.JComboBox<String> perfiles;
    private javax.swing.JLabel textoPerfil;
    private javax.swing.JLabel textoTitulo;
    private javax.swing.JLabel textoTitulo2;
    private javax.swing.JLabel userTxt;
    // End of variables declaration//GEN-END:variables
}
