/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

import com.clases.Docente;
import java.awt.Color;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import org.apache.poi.ss.usermodel.DataFormatter;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author sebas
 */
public class Login extends JFrame {

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        textoTitulo2 = new javax.swing.JLabel();
        inputPass = new javax.swing.JPasswordField();
        botonIngresar = new javax.swing.JButton();
        textoTitulo = new javax.swing.JLabel();
        perfiles = new javax.swing.JComboBox<>();
        textoRegistro = new javax.swing.JLabel();
        inputUser = new javax.swing.JTextField();
        userTxt = new javax.swing.JLabel();
        passTxt = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();
        botonRegistro = new javax.swing.JButton();
        textoPerfil1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conexión U");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(183, 214, 163));
        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        background.setForeground(new java.awt.Color(0, 0, 0));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoTitulo2.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        textoTitulo2.setForeground(new java.awt.Color(0, 0, 0));
        textoTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoTitulo2.setText("Inicio de sesión");
        textoTitulo2.setToolTipText("");
        textoTitulo2.setAutoscrolls(true);
        background.add(textoTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 300, 50));

        inputPass.setBackground(new java.awt.Color(255, 255, 255));
        inputPass.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        inputPass.setForeground(new java.awt.Color(153, 153, 153));
        inputPass.setToolTipText("");
        inputPass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.darkGray, java.awt.Color.darkGray));
        inputPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputPassMousePressed(evt);
            }
        });
        inputPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPassActionPerformed(evt);
            }
        });
        background.add(inputPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 230, 30));

        botonIngresar.setBackground(new java.awt.Color(255, 255, 255));
        botonIngresar.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        botonIngresar.setForeground(new java.awt.Color(0, 0, 0));
        botonIngresar.setText("Ingresar");
        botonIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonIngresarMouseClicked(evt);
            }
        });
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });
        background.add(botonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 120, 35));

        textoTitulo.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        textoTitulo.setForeground(new java.awt.Color(0, 0, 0));
        textoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoTitulo.setText("Conexión U");
        textoTitulo.setToolTipText("");
        textoTitulo.setAutoscrolls(true);
        background.add(textoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 300, 50));

        perfiles.setBackground(new java.awt.Color(255, 255, 255));
        perfiles.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        perfiles.setForeground(new java.awt.Color(0, 0, 0));
        perfiles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Docente", "Mentor", "Estudiante" }));
        perfiles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        perfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilesActionPerformed(evt);
            }
        });
        background.add(perfiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 150, 25));

        textoRegistro.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        textoRegistro.setForeground(new java.awt.Color(0, 0, 0));
        textoRegistro.setText("¿No tienes cuenta?");
        background.add(textoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 560, -1, 25));

        inputUser.setBackground(new java.awt.Color(255, 255, 255));
        inputUser.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        inputUser.setForeground(new java.awt.Color(153, 153, 153));
        inputUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inputUser.setText("Ingrese su nombre de usuario");
        inputUser.setToolTipText("");
        inputUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.darkGray, java.awt.Color.darkGray));
        inputUser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputUser.setMargin(new java.awt.Insets(0, 10, 0, 0));
        inputUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputUserFocusGained(evt);
            }
        });
        background.add(inputUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 230, 30));

        userTxt.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        userTxt.setForeground(new java.awt.Color(0, 0, 0));
        userTxt.setText("Usuario");
        background.add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, 25));

        passTxt.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        passTxt.setForeground(new java.awt.Color(0, 0, 0));
        passTxt.setText("Contraseña");
        background.add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, 25));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/logo_2023-2_300x300.png"))); // NOI18N
        background.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        botonVolver.setBackground(new java.awt.Color(255, 255, 255));
        botonVolver.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        botonVolver.setForeground(new java.awt.Color(0, 0, 0));
        botonVolver.setText("Volver");
        botonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonVolverMouseClicked(evt);
            }
        });
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        background.add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 120, 30));

        botonRegistro.setBackground(new java.awt.Color(255, 255, 255));
        botonRegistro.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        botonRegistro.setForeground(new java.awt.Color(0, 0, 0));
        botonRegistro.setText("Regístrate");
        botonRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegistroMouseClicked(evt);
            }
        });
        botonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistroActionPerformed(evt);
            }
        });
        background.add(botonRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, 120, 30));

        textoPerfil1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        textoPerfil1.setForeground(new java.awt.Color(0, 0, 0));
        textoPerfil1.setText("Seleccione un perfil");
        background.add(textoPerfil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, 25));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/background.png"))); // NOI18N
        background.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1016, 669));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPassActionPerformed

    private void inputPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputPassMousePressed

        if (inputUser.getText().isEmpty()) {
            inputUser.setText("Ingrese su nombre de usuario");
            inputUser.setForeground(Color.gray);
        }

    }//GEN-LAST:event_inputPassMousePressed

    private void botonIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIngresarMouseClicked

        if (inputUser.getText().equals("Ingrese su nombre de usuario") || inputUser.getText().equals("") || String.valueOf(inputPass.getPassword()).equals("****")) {
            JOptionPane.showMessageDialog(null, "Los campos están vacíos");
        } else if(perfiles.getSelectedItem().equals("Seleccionar")){
            JOptionPane.showMessageDialog(null, "No seleccionó ningún perfil");
        }
        

        switch (perfiles.getSelectedItem().toString()) {

            case "Docente" -> {

                String user = (inputUser.getText());
                char[] pass = inputPass.getPassword();
                String strPass = new String(pass);
                int validacion = datosCorrectos(user, strPass);
                if(validacion == 0){
                    JOptionPane.showMessageDialog(null, "Usuario no encontrado");
                } else if(validacion== -1){
                    JOptionPane.showMessageDialog(null, "Contraseña incorrecta");
                } else
                    JOptionPane.showMessageDialog(null, "bienvenido " + user);
            }
            case "Mentor" -> {
                JOptionPane.showMessageDialog(this, "Seleccionó el perfil de mentor");
            }
            case "Estudiante" -> {
                JOptionPane.showMessageDialog(this, "Seleccionó el perfil de estudiante");
            }
        }


    }//GEN-LAST:event_botonIngresarMouseClicked

    private void perfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilesActionPerformed

    }//GEN-LAST:event_perfilesActionPerformed

    private void inputUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputUserFocusGained

        if (inputUser.getText().equals("Ingrese su nombre de usuario")) {

            inputUser.setText("");
            inputUser.setForeground(Color.black);

        }

    }//GEN-LAST:event_inputUserFocusGained

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonIngresarActionPerformed

    private void botonVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVolverMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVolverMouseClicked

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistroMouseClicked

    private void botonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    public int datosCorrectos(String user, String pass) { // método que se usa para comparar la información que ingresa el usuario con los datos registrados en registros.xlsx

        ArrayList<Docente> registrosActuales = new ArrayList<>();
        int resultado=0;

        try {

            FileInputStream archivoExcel = new FileInputStream("src/datos/registros.xlsx");

            XSSFWorkbook libroExcel = new XSSFWorkbook(archivoExcel);
            XSSFSheet hoja = libroExcel.getSheetAt(0);

            DataFormatter dataFormatter = new DataFormatter();

            int primeraFila = hoja.getFirstRowNum() + 1;
            int ultimaFila = hoja.getLastRowNum();

            for (int i = primeraFila; i <= ultimaFila; i++) {
                Row fila = hoja.getRow(i);

                if (fila != null || fila.equals("")) {

                    String nombre = dataFormatter.formatCellValue(fila.getCell(0));
                    String apellido = dataFormatter.formatCellValue(fila.getCell(1));
                    int documento = Integer.parseInt(dataFormatter.formatCellValue(fila.getCell(2)));
                    String usuario = dataFormatter.formatCellValue(fila.getCell(3));
                    String password = dataFormatter.formatCellValue(fila.getCell(4));
                    String correo = dataFormatter.formatCellValue(fila.getCell(5));
                    String oficina = dataFormatter.formatCellValue(fila.getCell(6));

                    Docente docente = new Docente(nombre, apellido, documento, usuario, password, correo, true, oficina);
                    registrosActuales.add(docente);   
                }
            }

            Map<String, Docente> mapaDocentes = new HashMap<>(); //se crea un mapa para guardar la primayKey que sería el usuario como tipo string comparándolo con objetos de tipo docente

            for (Docente docente : registrosActuales) {
                mapaDocentes.put(docente.getUsuario(), docente);
            }

            if (mapaDocentes.containsKey(user)) {

                Docente docenteEncontrado = mapaDocentes.get(user);
                String passRegistrada = docenteEncontrado.getPassword();
                if (pass.equals(passRegistrada)) {
                    resultado = 1;
                } else {
                    resultado = -1;
                }

            } else {
                resultado = 0;
            }

        } catch (IOException e) {
            System.out.println(e.getMessage());
        }

        return resultado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton botonIngresar;
    private javax.swing.JButton botonRegistro;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel fondo;
    private javax.swing.JPasswordField inputPass;
    private javax.swing.JTextField inputUser;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel passTxt;
    private javax.swing.JComboBox<String> perfiles;
    private javax.swing.JLabel textoPerfil1;
    private javax.swing.JLabel textoRegistro;
    private javax.swing.JLabel textoTitulo;
    private javax.swing.JLabel textoTitulo2;
    private javax.swing.JLabel userTxt;
    // End of variables declaration//GEN-END:variables
}
