/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

import com.clases.Docente;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.poi.sl.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Daniel Henao
 */
public class RegistroDocente extends javax.swing.JFrame {

    /**
     * Creates new form RegistrlDocente
     */
    public RegistroDocente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroud = new javax.swing.JPanel();
        tituloTxt = new javax.swing.JLabel();
        inputOficina = new javax.swing.JTextField();
        inputApellido = new javax.swing.JTextField();
        inputDocumento = new javax.swing.JTextField();
        inputCorreo = new javax.swing.JTextField();
        inputNombre = new javax.swing.JTextField();
        inputUser = new javax.swing.JTextField();
        oficinaTxt = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JLabel();
        userTxt = new javax.swing.JLabel();
        passTxt = new javax.swing.JLabel();
        passcheckTxt = new javax.swing.JLabel();
        apellidoTxt = new javax.swing.JLabel();
        departamentoTxt = new javax.swing.JLabel();
        uniTxt = new javax.swing.JLabel();
        documentoTxt = new javax.swing.JLabel();
        inputPass = new javax.swing.JPasswordField();
        inputPassCheck = new javax.swing.JPasswordField();
        ciudades = new javax.swing.JComboBox<>();
        checkOficina = new javax.swing.JCheckBox();
        correoTxt = new javax.swing.JLabel();
        universidades = new javax.swing.JComboBox<>();
        departamentos = new javax.swing.JComboBox<>();
        ciudadTxt = new javax.swing.JLabel();
        botonRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        backgroud.setBackground(new java.awt.Color(183, 214, 163));
        backgroud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloTxt.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        tituloTxt.setForeground(new java.awt.Color(0, 0, 0));
        tituloTxt.setText("Registro Docente");
        backgroud.add(tituloTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 210, 60));

        inputOficina.setBackground(new java.awt.Color(255, 255, 255));
        inputOficina.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        inputOficina.setForeground(new java.awt.Color(0, 0, 0));
        inputOficina.setEnabled(false);
        backgroud.add(inputOficina, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 170, 25));

        inputApellido.setBackground(new java.awt.Color(255, 255, 255));
        inputApellido.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        inputApellido.setForeground(new java.awt.Color(0, 0, 0));
        backgroud.add(inputApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 170, 25));

        inputDocumento.setBackground(new java.awt.Color(255, 255, 255));
        inputDocumento.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        inputDocumento.setForeground(new java.awt.Color(0, 0, 0));
        backgroud.add(inputDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 170, 25));

        inputCorreo.setBackground(new java.awt.Color(255, 255, 255));
        inputCorreo.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        inputCorreo.setForeground(new java.awt.Color(0, 0, 0));
        inputCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCorreoActionPerformed(evt);
            }
        });
        backgroud.add(inputCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 170, 25));

        inputNombre.setBackground(new java.awt.Color(255, 255, 255));
        inputNombre.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        inputNombre.setForeground(new java.awt.Color(0, 0, 0));
        backgroud.add(inputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 170, 25));

        inputUser.setBackground(new java.awt.Color(255, 255, 255));
        inputUser.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        inputUser.setForeground(new java.awt.Color(0, 0, 0));
        backgroud.add(inputUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 170, 25));

        oficinaTxt.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        oficinaTxt.setForeground(new java.awt.Color(0, 0, 0));
        oficinaTxt.setText("Ubicación oficina");
        backgroud.add(oficinaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 150, -1));

        nombreTxt.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        nombreTxt.setForeground(new java.awt.Color(0, 0, 0));
        nombreTxt.setText("Nombre");
        backgroud.add(nombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 150, -1));

        userTxt.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        userTxt.setForeground(new java.awt.Color(0, 0, 0));
        userTxt.setText("Usuario");
        backgroud.add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 150, -1));

        passTxt.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        passTxt.setForeground(new java.awt.Color(0, 0, 0));
        passTxt.setText("Contraseña");
        backgroud.add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 150, -1));

        passcheckTxt.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        passcheckTxt.setForeground(new java.awt.Color(0, 0, 0));
        passcheckTxt.setText("Confirmar Contraseña");
        backgroud.add(passcheckTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 180, -1));

        apellidoTxt.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        apellidoTxt.setForeground(new java.awt.Color(0, 0, 0));
        apellidoTxt.setText("Apellido");
        backgroud.add(apellidoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 150, -1));

        departamentoTxt.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        departamentoTxt.setForeground(new java.awt.Color(0, 0, 0));
        departamentoTxt.setText("Departamento");
        backgroud.add(departamentoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 150, -1));

        uniTxt.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        uniTxt.setForeground(new java.awt.Color(0, 0, 0));
        uniTxt.setText("Universidad");
        backgroud.add(uniTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 150, -1));

        documentoTxt.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        documentoTxt.setForeground(new java.awt.Color(0, 0, 0));
        documentoTxt.setText("Documento de identidad");
        backgroud.add(documentoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 200, -1));

        inputPass.setBackground(new java.awt.Color(255, 255, 255));
        inputPass.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        inputPass.setForeground(new java.awt.Color(0, 0, 0));
        backgroud.add(inputPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 170, 25));

        inputPassCheck.setBackground(new java.awt.Color(255, 255, 255));
        inputPassCheck.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        inputPassCheck.setForeground(new java.awt.Color(0, 0, 0));
        backgroud.add(inputPassCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 170, 25));

        ciudades.setBackground(new java.awt.Color(255, 255, 255));
        ciudades.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        ciudades.setForeground(new java.awt.Color(0, 0, 0));
        ciudades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        ciudades.setEnabled(false);
        ciudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadesActionPerformed(evt);
            }
        });
        backgroud.add(ciudades, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, 170, 25));

        checkOficina.setBackground(new java.awt.Color(255, 255, 255));
        checkOficina.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        checkOficina.setForeground(new java.awt.Color(0, 0, 0));
        checkOficina.setText("¿Tiene oficina física?");
        checkOficina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkOficinaMouseClicked(evt);
            }
        });
        checkOficina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOficinaActionPerformed(evt);
            }
        });
        backgroud.add(checkOficina, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 170, 25));

        correoTxt.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        correoTxt.setForeground(new java.awt.Color(0, 0, 0));
        correoTxt.setText("Correo");
        backgroud.add(correoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 150, -1));

        universidades.setBackground(new java.awt.Color(255, 255, 255));
        universidades.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        universidades.setForeground(new java.awt.Color(0, 0, 0));
        universidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        universidades.setEnabled(false);
        universidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                universidadesActionPerformed(evt);
            }
        });
        backgroud.add(universidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, 170, 25));

        departamentos.setBackground(new java.awt.Color(255, 255, 255));
        departamentos.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        departamentos.setForeground(new java.awt.Color(0, 0, 0));
        departamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Antioquia", "Córdoba", "Bogota D.C.", "Caldas" }));
        departamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departamentosActionPerformed(evt);
            }
        });
        backgroud.add(departamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 170, 25));

        ciudadTxt.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        ciudadTxt.setForeground(new java.awt.Color(0, 0, 0));
        ciudadTxt.setText("Ciudad");
        backgroud.add(ciudadTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 150, -1));

        botonRegistro.setBackground(new java.awt.Color(255, 255, 255));
        botonRegistro.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        botonRegistro.setForeground(new java.awt.Color(0, 0, 0));
        botonRegistro.setText("Registrase");
        botonRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegistroMouseClicked(evt);
            }
        });
        backgroud.add(botonRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 530, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroud, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroud, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCorreoActionPerformed

    private void checkOficinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOficinaActionPerformed


    }//GEN-LAST:event_checkOficinaActionPerformed

    private void checkOficinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkOficinaMouseClicked

        if (checkOficina.isSelected()) {

            inputOficina.setEnabled(true);

        } else {
            inputOficina.setText("");
            inputOficina.setEnabled(false);
        }
    }//GEN-LAST:event_checkOficinaMouseClicked

    private void departamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departamentosActionPerformed

        if (departamentos.getSelectedItem().toString() != "Seleccionar") {

            ciudades.setEnabled(true);
            String[] ciudadesAnt = new String[]{"Medellín", "Sabaneta"};

            if (departamentos.getSelectedItem().toString() == "Antioquia") {

                //municipios.addItem("");
                for (int i = 0; i < ciudadesAnt.length; i++) {
                    ciudades.addItem(ciudadesAnt[i]);
                }

            }

        } else {
            ciudades.setEnabled(false);
        }


    }//GEN-LAST:event_departamentosActionPerformed

    private void ciudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadesActionPerformed


    }//GEN-LAST:event_ciudadesActionPerformed

    private void universidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_universidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_universidadesActionPerformed

    private void botonRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistroMouseClicked
      
    }//GEN-LAST:event_botonRegistroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroDocente().setVisible(true);
            }
        });
    }

    public boolean validarDatos() {

        boolean datosValidados = true;
        
        char [] pass1 = inputPass.getPassword();
        char [] pass2 = inputPassCheck.getPassword();
        
        String strPass1 = new String(pass1);
        String strPass2 = new String(pass2);
        
        if (!strPass1.equals(strPass2)) {
            
            datosValidados = false;
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden");
        }
            
        Arrays.fill(pass1, ' ');
        Arrays.fill(pass2, ' ');
        
        strPass1 = null;
        strPass2 = null;
        

        if (inputNombre.getText().isEmpty()
                || inputApellido.getText().isEmpty()
                || inputDocumento.getText().isEmpty()
                || inputUser.getText().isEmpty()
                || inputPass.getPassword().length == 0
                || inputPassCheck.getPassword().length == 0
                || inputCorreo.getText().isEmpty()
                || (checkOficina.isSelected() && inputOficina.getText().isEmpty())) {

            datosValidados = false;
            JOptionPane.showMessageDialog(this, "Favor llenar todos los campos ");
        }


        return datosValidados;

    }
    
    public void agregarDocente(Docente docente){
        
        boolean datosOk = validarDatos();
 
        if(datosOk == true){
   
            docente.setNombre(inputNombre.getText());
            docente.setApellido(inputApellido.getText());
            docente.setDocumento(Integer.parseInt(inputDocumento.getText()));
            docente.setUsuario(inputUser.getText());
            docente.setCorreo(inputCorreo.getText());
            if (checkOficina.isSelected()){docente.setCheckOficina(true);}else{docente.setCheckOficina(false);}
            docente.setOficina(inputOficina.getText());
            
            char [] pass1 = inputPass.getPassword();
            String strPass1 = new String(pass1);
            docente.setPassword(strPass1);
            
            System.out.println("Nombre: " + docente.getNombre() + " Apellido: " + docente.getApellido() + " Documento: " + docente.getDocumento() +
                " Usuario " + docente.getUsuario() + " Contraseña " + docente.getPassword() + " Correo " + docente.getCorreo() +
                " Tiene oficina " + docente.getCheckOficina() +" Oficina " + docente.getOficina());
            
        }   
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoTxt;
    private javax.swing.JPanel backgroud;
    private javax.swing.JButton botonRegistro;
    private javax.swing.JCheckBox checkOficina;
    private javax.swing.JLabel ciudadTxt;
    private javax.swing.JComboBox<String> ciudades;
    private javax.swing.JLabel correoTxt;
    private javax.swing.JLabel departamentoTxt;
    private javax.swing.JComboBox<String> departamentos;
    private javax.swing.JLabel documentoTxt;
    private javax.swing.JTextField inputApellido;
    private javax.swing.JTextField inputCorreo;
    private javax.swing.JTextField inputDocumento;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputOficina;
    private javax.swing.JPasswordField inputPass;
    private javax.swing.JPasswordField inputPassCheck;
    private javax.swing.JTextField inputUser;
    private javax.swing.JLabel nombreTxt;
    private javax.swing.JLabel oficinaTxt;
    private javax.swing.JLabel passTxt;
    private javax.swing.JLabel passcheckTxt;
    private javax.swing.JLabel tituloTxt;
    private javax.swing.JLabel uniTxt;
    private javax.swing.JComboBox<String> universidades;
    private javax.swing.JLabel userTxt;
    // End of variables declaration//GEN-END:variables
}
