/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ppi_conexion_poli;

import javax.swing.JOptionPane;

/**
 *
 * @author sebas
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        textoTitulo = new javax.swing.JLabel();
        inputUser = new javax.swing.JTextField();
        separator1 = new javax.swing.JSeparator();
        passUser = new javax.swing.JPasswordField();
        separator2 = new javax.swing.JSeparator();
        botonIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conexión Poli");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        background.setForeground(new java.awt.Color(0, 0, 0));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoTitulo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        textoTitulo.setForeground(new java.awt.Color(0, 0, 0));
        textoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoTitulo.setText("Conexión Poli");
        textoTitulo.setAutoscrolls(true);
        background.add(textoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, 20));

        inputUser.setBackground(new java.awt.Color(255, 255, 255));
        inputUser.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        inputUser.setForeground(new java.awt.Color(0, 0, 0));
        inputUser.setText("Ingrese su nombre de usuario");
        inputUser.setBorder(null);
        inputUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputUserMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inputUserMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputUserMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                inputUserMouseReleased(evt);
            }
        });
        inputUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUserActionPerformed(evt);
            }
        });
        inputUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputUserKeyPressed(evt);
            }
        });
        background.add(inputUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 400, 20));

        separator1.setBackground(new java.awt.Color(255, 255, 255));
        separator1.setForeground(new java.awt.Color(0, 0, 0));
        background.add(separator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 400, 20));

        passUser.setBackground(new java.awt.Color(255, 255, 255));
        passUser.setForeground(new java.awt.Color(0, 0, 0));
        passUser.setText("****");
        passUser.setToolTipText("");
        passUser.setBorder(null);
        passUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passUserMousePressed(evt);
            }
        });
        passUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passUserActionPerformed(evt);
            }
        });
        background.add(passUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 400, -1));

        separator2.setBackground(new java.awt.Color(255, 255, 255));
        separator2.setForeground(new java.awt.Color(0, 0, 0));
        background.add(separator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 400, 20));

        botonIngresar.setBackground(new java.awt.Color(153, 153, 153));
        botonIngresar.setForeground(new java.awt.Color(0, 0, 0));
        botonIngresar.setText("Ingresar");
        botonIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonIngresarMouseClicked(evt);
            }
        });
        background.add(botonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1016, 659));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUserActionPerformed

    private void passUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passUserActionPerformed

    private void inputUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputUserMouseClicked
        
        
        
    }//GEN-LAST:event_inputUserMouseClicked

    private void inputUserMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputUserMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUserMouseReleased

    private void inputUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputUserMouseExited
        
    }//GEN-LAST:event_inputUserMouseExited

    private void inputUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputUserMousePressed
        
        if (inputUser.getText().equals("Ingrese su nombre de usuario")){
            inputUser.setText("");       
        }
        
        if(String.valueOf(passUser.getPassword()).isEmpty()){
            
            passUser.setText("****");
        
        }
        
    }//GEN-LAST:event_inputUserMousePressed

    private void passUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passUserMousePressed
        
        if(String.valueOf(passUser.getPassword()).equals("****")){
            
            passUser.setText("");
        }
        
        if (inputUser.getText().isEmpty()){
            inputUser.setText("Ingrese su nombre de usuario");
        }
        
    }//GEN-LAST:event_passUserMousePressed

    private void botonIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIngresarMouseClicked
        
        if (inputUser.getText().equals("Ingrese su nombre de usuario") || inputUser.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Los campos están vacíos");
        } else{
            JOptionPane.showMessageDialog(null, "El usuario ingresado es " + inputUser.getText());
        }
    }//GEN-LAST:event_botonIngresarMouseClicked

    private void inputUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputUserKeyPressed
        // TODO add your handling code here:  
    }//GEN-LAST:event_inputUserKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton botonIngresar;
    private javax.swing.JTextField inputUser;
    private javax.swing.JPasswordField passUser;
    private javax.swing.JSeparator separator1;
    private javax.swing.JSeparator separator2;
    private javax.swing.JLabel textoTitulo;
    // End of variables declaration//GEN-END:variables
}
