/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.perfilestudiante;

import com.clases.Docente;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.DataFormatter;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author sebas
 */
public class Profesores extends javax.swing.JFrame {

    /**
     * Creates new form Profesores
     */
    public Profesores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        profesoresTxt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDocentes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Profesores");
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(1000, 630));
        setResizable(false);

        background.setBackground(new java.awt.Color(204, 204, 204));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profesoresTxt.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        profesoresTxt.setForeground(new java.awt.Color(0, 0, 0));
        profesoresTxt.setText("Profesores");
        profesoresTxt.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        background.add(profesoresTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 130, -1));

        tablaDocentes.setAutoCreateRowSorter(true);
        tablaDocentes.setBackground(new java.awt.Color(204, 204, 204));
        tablaDocentes.setBorder(new javax.swing.border.MatteBorder(null));
        tablaDocentes.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        tablaDocentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaDocentes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tablaDocentes);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 860, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profesores().setVisible(true);
            }
        });
        llenarTabla();
    }
    
    public static void llenarTabla(){
        
        ArrayList<Docente> registrosActuales = new ArrayList<>();
        
        try {

            FileInputStream archivoExcel = new FileInputStream("src/datos/registros.xlsx");

            XSSFWorkbook libroExcel = new XSSFWorkbook(archivoExcel);
            XSSFSheet hoja = libroExcel.getSheetAt(0);

            DataFormatter dataFormatter = new DataFormatter();

            int primeraFila = hoja.getFirstRowNum() + 1;
            int ultimaFila = hoja.getLastRowNum();

            for (int i = primeraFila; i <= ultimaFila; i++) {
                Row fila = hoja.getRow(i);
                if (fila != null || fila.equals("")) {
                    
                    String nombre = dataFormatter.formatCellValue(fila.getCell(0));
                    String apellido = dataFormatter.formatCellValue(fila.getCell(1));
                    int documento = Integer.parseInt(dataFormatter.formatCellValue(fila.getCell(2)));
                    String usuario = dataFormatter.formatCellValue(fila.getCell(3));
                    String password = dataFormatter.formatCellValue(fila.getCell(4));
                    String correo = dataFormatter.formatCellValue(fila.getCell(5));
                    String oficina = dataFormatter.formatCellValue(fila.getCell(6));

                    Docente docente = new Docente(nombre, apellido, documento, usuario, password, correo, true, oficina);
                    registrosActuales.add(docente);    
                }
            }
            
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nombre");
        model.addColumn("Apellido");
        model.addColumn("Correo");
        model.addColumn("Oficina");
        
        for (Docente d: registrosActuales){
            String nombre = d.getNombre();
            String apellido = d.getApellido();
            String correo = d.getCorreo();
            String oficina = d.getOficina();
            
            model.addRow(new Object[]{nombre, apellido, correo, oficina});
        }
        
        tablaDocentes.setModel(model);
               
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel profesoresTxt;
    private static javax.swing.JTable tablaDocentes;
    // End of variables declaration//GEN-END:variables
}
